#pragma once
#include <stdint.h>
namespace basic{
enum OctopusConnStatus:uint8_t{
	OCTOPUS_CONN_MIN,
	OCTOPUS_CONN_CONNECTING,
	OCTOPUS_CONN_CONNECTED,
	OCTOPUS_CONN_DISCONN,
};
enum OctopusSignalCode:uint8_t{
	OCTOPUS_SIG_MIN,
	OCTOPUS_SIG_CONN_CONNECTING,
	OCTOPUS_SIG_CONN_CONNECTED,
	OCTOPUS_SIG_CONN_FAILED,
	OCTOPUS_SIG_CONN_DISCONN,
	OCTOPUS_SIG_DST_CONNECTED,
	OCTOPUS_SIG_DST_FAILED,
};
enum OctopusHandRole:uint8_t{
	OCTOPUS_HAND_CLIENT,
	OCTOPUS_HAND_SERVER,
};
enum OctopusDispatcherRole:uint8_t{
	OCTOPUS_DISPATCHER_CLIENT,
	OCTOPUS_DISPATCHER_SERVER,
};
enum OctopusMessage:uint8_t{
	OCTOPUS_MSG_MIN,
	OCTOPUS_MSG_META,
	OCTOPUS_MSG_DST_CONNECTED,
	OCTOPUS_MSG_DST_FAILED,
	OCTOPUS_MSG_PING,
	OCTOPUS_MSG_PONG,
};
enum OctopusMessageFlag:uint8_t{
	OCTOPUS_META_MIN_FLAG,
	OCTOPUS_META_FLAG=0x01,
	OCTOPUS_META_ACK_FLAG=0x02,
};
}
